### PR TITLE
updates for latest OF & a few bug fixes

### LINKED ISSUE #99: Missing / erroneous GetWorldCenter()
I'm using the ofxBox2d plugin in of 0.9 for my physics. As a start, I want a cube to jump. Without any additional velocities applied, this should result in a movement on the vertical axis.

My objects' physics: 
box.setPhysics(10,0,0);

The impulse used for jumping:
box.addImpulseForce(ofVec2f(0,-5), box.getPosition());

Unfortunately, the impulse doesn't seem to be applied at the object's centre of mass, resulting in a crazy rotation. On http://www.iforce2d.net/b2dtut/jumping2 , it says to pass box.GetWorldCenter() as a second argument, but this is not available in ofxBox2d. I tried to fetch this information from box.body->getWorldCentre(), but these values are not very helpful.

This question is also in the OF forums: http://forum.openframeworks.cc/t/why-does-my-vertical-impulse-in-ofxbox2d-results-in-rotation/21327

### PR DESCRIPTION
**Pull request by danomatika**
## Updates

Updated all examples. Renamed testApp to ofApp. Regenerated Xcode projects. A bunch of whitespace consistency fixes.

## Fixes

Fixed deprecations with latest OF.

Added an add-on_config.make with the -DNO_TIMER define needed to build the triangle lib in Visual Studio aka #49.

Added body getWorldPosition() to fix #99. Tested and works as desired.

## Suggestion

Since testApp is now ofApp, the project files for the other platforms need to be regenerated as well. At this point, the ProjectGenerator is pretty reliable so I suggest we remove *all* the project files. People can simply generate them with the PG. This works very well for my addons since I don't have to keep the project files up to date myself.

If desired, I can do go ahead and remove them in another commit to this PR.

### CODE REVIEW

**Comment by danomatika** [comment]
Pinging @kylemcdonald @NickHardeman @ilektron @danoli3

**Comment by kylemcdonald** [comment]
going to merge this immediately, going to wait a little longer before completely removing the project files. my feeling is that people are still learning to rely on the PG.

**Comment by danomatika** [comment]
We will need to regenerate the VS & CB files then. I haven't had any issues yet with people using the PG, mainly since I include information on how to use it.

**Comment by danoli3** [comment]
I tested the changes today! Looks great! Thanks @danomatika

**Pull request merged**
